[build]
command = "npm run build"
publish = "dist"

[build.environment]
REACT_APP_URL_HOSTNAME = "https://react-wasm-video-editor.netlify.app"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "browsing-topics=(self)"
